### ISSUE TITLE
Bamboo checkout of git branch

### ISSUE THREAD

**Issue by digitalmedia** [krosenvold/bgit#10]
Hi Kristian,

Not sure this is really an issue, or a misunderstanding of Bamboo and Git on my part. I haven't seen a forum for bgit, so I'm posting this here, any info appreciated.

When setting bgit properties in Bamboo, if I set the branch to anything other than 'master', I seem to get the same source as the branch indeed. This is fine. However if I navigate into the Bamboo 'build-dir' where the source has been checked out, and run a 'git branch' command, it comes back as *master.

The source is not master however, it is the branch as requested. So this is strictly a local thing. Perhaps I shouldn't be tinkering around in Bamboo's 'build-dir', but thought I would raise this point as it had me rather confused for a while. I'm still pretty new to Git, although have been using CVS since 2000, and SVN in the last few years.

Is this ok? And should I just forget about it?
Any feedback appreciated.
- Richard (digitalmedia)

**Comment by digitalmedia** [comment]
Whoa - I think I got bgit and Andy Pol's GitHub plugins confused... the above refers to the GitHub plugin, please ignore, I'll post on his wiki. Apologies.
- Richard

**Comment by krosenvold** [comment]
Btw; The bgit plugin works equally well with github and supports more git-fu ;)

**Comment by digitalmedia** [comment]
Thanks Kristian - actually I'm using bgit, but also have GitHub plugin as well, and found the (apparent, not confirmed) issue with GitHub plugin... bgit works quite satisfactorily! Any workflow suggestions for getting a tag exported, then built (via Bamboo)? Currently jumping through some hoops to do this, it's working but just wondered if something more elegant exists. Cheers.
