### ISSUE TITLE
Cannot checkout, where to get help?

### ISSUE THREAD

**Issue by dmitrybelyakov** [krosenvold/bgit#14]
Hi Kristian,

Please excuse my writing to issue tracker, but i really need some help with setting up bgit. It all went fine on my OSX, but i cannot do initial checout on our CI server.

Bamboo is running as sytem service by 'bamboo' user. If i switch to bamboo user i can actually checkout repository from console (so ssh keys are ok i guess). 

But when i trigger a Bamboo build it starts barking at me with this: 

Error occurred while executing the build for PROJECT-QUICK-9 : 438000: Error calling git-status - git status error message: { 1. error: unknown switch `a'  } Although it DID initial code checkout to  'checkout' directory project build directory.

So i have no idea what can be wrong here. Please help me! 
I'm on Centos5 with bgit 1.2 and Bamboo 2.2.5

Dmitry.

**Comment by krosenvold** [comment]
just build latest from source. this is fixed. Will make a release soon ...

**Comment by dmitrybelyakov** [comment]
Ok, actually that's what i'm doing right now, thanks for the tip.
