### ISSUE TITLE
Logging into System.out spams bamboo.log

### ISSUE THREAD

**Issue by dmatej** [krosenvold/bgit#16]
The class ProcessUtilities writes into System.out and System.err - you should better use some Logger just like in the GitRepository.

Our projects use Repository Polling strategy and git plugin writes all git orders again and again into the log file.

**Comment by dmatej** [comment]
It is fixed here: http://github.com/dmatej/bgit/downloads
I don't know how to send a patch - I cannot send e-mails from command line ... so I have created my own fork.

**Comment by krosenvold** [comment]
Thanks.
