### ISSUE TITLE
Allow using HTTP(S) with input for repository authentication credentials

### ISSUE THREAD

**Issue by lahma** [krosenvold/bgit#17]
Would it be somehow possible to give user name and password to use in source repository configuration with HTTP support? 

We are hosting Git with Apache that uses LDAP autentication and it would be a great feature to have (just like we have it for SVN and CVS).

**Comment by krosenvold** [comment]
I will happly review any patch received for this.

**Comment by lahma** [comment]
I was afraid of that, gotta see if I find the time :)

**Comment by trskinner** [comment]
I'd love this too!

**Comment by lahma** [comment]
Bamboo 3.0 has this built-in and works nicely. Closing this as obsolete.
