### ISSUE TITLE
Maven build fails b/c of dependency on jna:jar

### ISSUE THREAD

**Issue by asalant** [krosenvold/bgit#2]
'mvn install' after clean checkout of the plugin head fails with:

```
ERROR] BUILD ERROR
[INFO] ------------------------------------------------------------------------
[INFO] Failed to resolve artifact.

Missing:
----------
1) com.atlassian.3rdparty.net.java.dev.jna:jna:jar:3.0.3

...

  Path to dependency: 
      1) com.atlassian.labs.bamboo.git:git-plugin:jar:1.1.5
      2) com.atlassian.bamboo:atlassian-bamboo-core:jar:2.2
      3) com.atlassian.3rdparty.net.java.dev.jna:jna:jar:3.0.3
```

The fix (I believe) is to exclude the dependency:
    diff --git a/pom.xml b/pom.xml
    index 523b4b0..b942014 100644
    --- a/pom.xml
    +++ b/pom.xml
    @@ -97,6 +97,12 @@
                 <groupId>com.atlassian.bamboo</groupId>
                 <artifactId>atlassian-bamboo-core</artifactId>
                 <version>2.2</version>
    +            <exclusions>
    +                <exclusion>
    +                    <groupId>com.atlassian.3rdparty.net.java.dev.jna</groupId>
    +                    <artifactId>jna</artifactId>
    +                </exclusion>
    +            </exclusions>
             </dependency>
             <dependency>
                 <artifactId>junit</artifactId>

Note that with this change I can now build the project but three tests fail. I can build the jar by skipping tests but I'm not sure if the tests are failing b/c of this excluded jar.

I would not be doing this if I could download a 1.5 precompiled jar but I couldn't find one. I'll create an issue for that.

**Comment by krosenvold** [comment]
The issue has been reported to atlassian support, since the jar file went AWOL in their repos at least a week ago. I escalated the issue with atlassian support right now. If they do not fix this RSN I suggest you also file an issue with atlassian. I will keep this issue open until atlassian fixes it. (They actually sent me the jar file in an email !!!)

**Comment by krosenvold** [comment]
Fixed with a pom.xml update onhead of master. Latest version builds well. Please note that you _must_ have git:// protocol access to github to make tests run.
