### ISSUE TITLE
bamboo 2.6.1

### ISSUE THREAD

**Issue by ssmithstone** [krosenvold/bgit#20]
any chance of a plugin version for the new bamboo ?

Cheers

**Comment by acydburn** [comment]
Would like to know too. :) Haven't yet tried it with 2.6 though.

**Comment by jhobbs** [comment]
I voted this issue up.  Upgraded to 2.6.2 without checking for support first :(

**Comment by krosenvold** [comment]
It works fine with 2.6.x

**Comment by jhobbs** [comment]
If that is the case, can you please update the 'supported versions' on the front page of this github?
