### ISSUE TITLE
Bamboo 3 support

### ISSUE THREAD

**Issue by trevormarshall** [krosenvold/bgit#26]
Hey Kristian, looks like Atlassian hasn't provided an upgrade path from your plugin to theirs in 3.0. Noticed when staging an upgrade of the Spring build box tonight. Just wondering if you are going to keep up the good work, or if we should plan a move.

Cheers,
Trevor

**Comment by krosenvold** [comment]
You should plan to move ;)  The plugin will stay here, but I will not be doing further development and I will not be testing it for bamboo 3.X.

**Comment by trevormarshall** [comment]
This is a real shame, the Atlassian plugin does not support submodules :(

**Comment by krosenvold** [comment]
I'll see how much work it is to get it built for 3.x. As long as there's demand I suppose it's not that big a deal.

**Comment by pstefaniak** [comment]
Hello,
I reckon David Matejcek has done 3.0.1 port of bgit plugin. https://github.com/dmatej/bgit#readme - might be working with 3.1, might be not...
