### ISSUE TITLE
Latest release (1.5) not available for download

### ISSUE THREAD

**Issue by asalant** [krosenvold/bgit#3]
1.5 is latest release.

1.3 is available from http://labs.atlassian.com/wiki/display/BGIT/Home
1.0 is available from http://confluence.atlassian.com/display/BAMEXT/Git+Repository+Plugin

I was able to build 1.5 from source but ran into Maven dependency issues that I had to work around (see my other bug report).

**Comment by krosenvold** [comment]
I have added a download link on the wiki page. http://wiki.github.com/krosenvold/bgit

**Comment by krosenvold** [comment]
Closing this issue
