### ISSUE TITLE
current master does not run in Bamboo 2.5

### ISSUE THREAD

**Issue by RangerRick** [krosenvold/bgit#5]
I've ripped it out in my fork so I can get Bamboo back up and running after upgrade, but I'm not sure what's supposed to replace it.

http://github.com/RangerRick/bgit/commit/a5740eaec2d54bfaa4bc4749aa97f905a7996329 has my change, if you're interested.

**Comment by krosenvold** [comment]
Thanks for the patch. Applied in 1.1.7. Also works on 2.4.3
